apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ahmed862/frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://backend-service:3001/api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000 # Frontend app port
    targetPort: 3000
    nodePort: 32000 # Port accessible on the cluster nodes
  type: NodePort
